### ISSUE TITLE
Process hangs when using --stdio

### ISSUE THREAD

**Issue by mcMickJuice** [square/babel-codemod#13]
Hello, thanks for writing this piece of software!

Everything's working great for me from a file transformation perspective however I am unable to get the `--stdio` switch feature to work.  The process hangs when this switch is provided.

Below is a link to a repo that repros this issue. I've included an actual codemod as well as a noop one.  All scenarios are enumerated out in package.json scripts section.

https://github.com/mcMickJuice/babel-codemod-stdio-issue

**Comment by eventualbuddha** [comment]
Thanks for using the project! I hope it's proving useful. The `--stdio` option is intended to be used without specifying file paths and will read JavaScript from stdin and print the result to stdout. The process appears to hang because it's waiting for input. I hope that helps! 

It would help me improve the documentation if I understood how you expected it to work. Mind clarifying what you expected?

**Comment by mcMickJuice** [comment]
silly me.

I was expecting it to work like [jscodeshifts dry run feature ](https://github.com/facebook/jscodeshift#usage-cli).

**Comment by eventualbuddha** [comment]
Ah, I see. I haven't prioritized that feature because I figure git can effectively reset changes to files to get a similar workflow. Is be happy to accept a pull request for it, though!
