### ISSUE TITLE
extra semicolon inserted on "use strict"; ("use strict";;)

### ISSUE THREAD

**Issue by MagicDuck** [square/babel-codemod#157]
Hi, I don't know if this is actually a recast issue. Feel free to redirect me :)
When I apply a codemod to code that contains `"use strict";`, I get the following result:
```
    "use strict";;
```
Appreciate your help!

**Comment by eventualbuddha** [comment]
Can you provide some more details? Some code and a codemod that triggers it? It's often useful to share as a astexplorer.net link.

**Comment by eventualbuddha** [comment]
Yeah, I tried the same thing as you by removing the statement. This appears to be a recast bug. Maybe file a bug there?

cc @benjamn

**Comment by eventualbuddha** [comment]
Odd. I’ll take a look again. babel-codemod should be using babel 7.

**Comment by MagicDuck** [comment]
Many thanks :)

**Comment by eventualbuddha** [comment]
I ran across this bug again when I was upgrading various `@babel` packages, and I finally figured out the cause. I figured I'd write some stuff here while it's still fresh in my mind.

> I am starting to have some doubts though, would this be considered ok since you are technically removing the identifier and not the statement?

We wondered about the behavior of removing the `expression` of an `ExpressionStatement` without removing the `ExpressionStatement` itself. It turns out that if you `path.remove()` an expression in this way [`@babel/traverse` will automatically remove the parent for you](https://github.com/babel/babel/blob/5fb4d84a33351c13057dc542513a3fe2309e08b0/packages/babel-traverse/src/path/lib/removal-hooks.js#L27-L33), so that explains why removing the parent had the same behavior.

> This appears to be a recast bug. 

This turned out to be true, but the reason was somewhat interesting. In Babel 6 they changed the AST to add a `directives` property to `BlockStatement`. Instead of `"use strict";` being parsed as an `ExpressionStatement`, it is not considered a statement and is instead included as a `Directive` node. [@hzoo added initial support for printing directives in recast](https://github.com/benjamn/recast/pull/299), with the part relevant to this discussion here:

https://github.com/benjamn/recast/blob/63fbaf97909bbd86a7aaa77bb176c2c124455a84/lib/printer.js#L547-L556

Notice that it unconditionally adds a `";"` part to the output, regardless of what is included by the previous part: `print(childPath).indent(options.tabWidth)`. This is the bug. Why? Because the `Directive` node's range includes the semicolon if present:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/1938/62385161-2c0ea080-b509-11e9-9b67-49038cf14f93.png">

And since recast sees that the `Directive` is unchanged, it prints it as-is. When recast prints a newly-generated `Directive`, it simply prints its contained `DirectiveLiteral` value, which does not include the semicolon:

https://github.com/benjamn/recast/blob/63fbaf97909bbd86a7aaa77bb176c2c124455a84/lib/printer.js#L758-L762

Note the `[0, 12)` range of the `DirectiveLiteral` and the `[0, 13)` range of the `Directive`. The difference is the `;`. Here's how recast prints a directive that it didn't originally parse:

```js
> recast.print(t.directive(t.directiveLiteral('use strict')))
PrintResult { code: '"use strict"' } // no semicolon
```

So how do we fix it? We need to add a semicolon if there isn't one already, and fortunately `printer.ts` already has a utility to help with that called `maybeAddSemicolon`. It's a good thing this helper already exists, because the result of this internal `print` is not a string or an array but a `Lines` instance which is a fair amount more complicated.

https://github.com/benjamn/recast/blob/63fbaf97909bbd86a7aaa77bb176c2c124455a84/lib/printer.js#L1979-L1984

And now, three years later, the bug is finally fixed in https://github.com/benjamn/recast/pull/617.
