### ISSUE TITLE
path.addComment() does not seem to work

### ISSUE THREAD

**Issue by MagicDuck** [square/babel-codemod#168]
Hi,

I am trying to use `path.addComment()` to insert a comment into the code. The issue is that I don't see any result with `ast explorer` or `babel-codemod`. I've asked around on the babeljs slack channel and was told `ast explorer` has one customization that might interfere with comments. I am wondering if `babel-codemod` has the same customization. Here's the snippet I was playing with:
https://astexplorer.net/#/gist/3773ea0b4c55ee68e6b6d9929f3ecab7/2a6fa8635ac12a1fcd35d3e078fe41e3b58821ec

Much appreciate any help :)

**Comment by eventualbuddha** [comment]
I was able to get it to work by manipulating the `comments` array directly: https://astexplorer.net/#/gist/3773ea0b4c55ee68e6b6d9929f3ecab7/22666ed0d86df8dcf6d65314b5bb2470f8321fa7

Not sure why `path.addComment` doesn't work, but at least you have a workaround!

**Comment by MagicDuck** [comment]
Thanks @eventualbuddha , you da best 😁!

**Comment by cameron-martin** [comment]
This seems to be due to differences in the way that recast's default parser & babel attach comments to the AST: [recast adds a `comments` property](https://astexplorer.net/#/gist/d69244558bbb04ebf50aca3b99b1b07e/60e2f938090d147d6bfb5e89e6262073be10b0d3) and [babel adds a `leadingComments` and `trailingComments` property](https://astexplorer.net/#/gist/d69244558bbb04ebf50aca3b99b1b07e/52003aa92df5783344c7625505cebf47d03ab52a).

The strange part is that I thought recast uses esprima as the default parser, and [esprima seems to use the babel convention](https://astexplorer.net/#/gist/d69244558bbb04ebf50aca3b99b1b07e/f58ba06ba4b7b1a31cb5aac53ae58be494306a2d).
