### ISSUE TITLE
Support globs?

### ISSUE THREAD

**Issue by kentcdodds** [square/babel-codemod#4]
Globs (using [`glob`](https://npmjs.com/package/glob)) are really common for packages like this one. It would be very nice to be able to specify a glob for the transformation.

**Comment by eventualbuddha** [comment]
@kentcdodds thanks for the suggestion! Do you have an example of another project that does this? I'd assumed allowing the shell to expand globs for us would suffice, but maybe I'm missing something?

**Comment by kentcdodds** [comment]
Unfortunately shell glob is very subjective across environments, which is why `glob` exists. My [`split-guide`](https://github.com/kentcdodds/split-guide) project does this as does [`prettier-eslint-cli`](https://github.com/prettier/prettier-eslint-cli).

Also, I noticed that you're constructing CLI options by hand. You might think about looking into [`yargs`](http://yargs.js.org/) instead which gives a much more declarative API for accomplishing what you're doing.

**Comment by eventualbuddha** [comment]
Just merged glob support, should be out in 1.1.0. As for `yargs`, I typically just roll my own because I often end up doing something that is difficult/impossible to support using an abstraction like `yargs`. Right now that's not the case with this project, though. If it becomes annoying to maintain I'll look into it.
